package com.epam.laboratory.workObjects;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.19 at 10:49:02 AM MSK 
//

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


///**
// * <p>Java class for anonymous complex type.
// *
// * <p>The following schema fragment specifies the expected content contained within this class.
// *
// * <pre>
// * &lt;complexType>
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="gem" maxOccurs="unbounded" minOccurs="0">
// *           &lt;complexType>
// *             &lt;complexContent>
// *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *                 &lt;sequence>
// *                   &lt;element name="visualParameters">
// *                     &lt;complexType>
// *                       &lt;complexContent>
// *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *                           &lt;sequence>
// *                             &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *                             &lt;element name="numberOfFaces" type="{http://www.w3.org/2001/XMLSchema}byte"/>
// *                             &lt;element name="transparency" type="{http://www.w3.org/2001/XMLSchema}float"/>
// *                           &lt;/sequence>
// *                         &lt;/restriction>
// *                       &lt;/complexContent>
// *                     &lt;/complexType>
// *                   &lt;/element>
// *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *                   &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *                   &lt;element name="preciousness" type="{http://www.w3.org/2001/XMLSchema}string"/>
// *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}float"/>
// *                 &lt;/sequence>
// *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
// *               &lt;/restriction>
// *             &lt;/complexContent>
// *           &lt;/complexType>
// *         &lt;/element>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//        "gem"
//})
//@XmlRootElement(name = "Gems")

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="visualParameters">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="numberOfFaces" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="transparency" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preciousness" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "visualParameters",
        "name",
        "origin",
        "preciousness",
        "value"
})
@JsonRootName(value = "gem")
public class Gem {

    public Gem(String color, int id, String name, byte numberOfFaces, String origin, String preciousness, byte transparency, float value) {

        this.visualParameters = new VisualParameters(color, numberOfFaces, transparency);
        this.name = name;
        this.origin = origin;
        this.preciousness = preciousness;
        this.value = value;
        this.id = id;
    }

    public VisualParameters getVisualParameters() {
        return visualParameters;
    }

    public void setVisualParameters(String color, Byte numberOfFaces, Float transparency){
        visualParameters.setVisualParameters(color, numberOfFaces, transparency);
    }

    @JsonProperty("VisualParameters")
    @XmlElement(required = true)
    protected VisualParameters visualParameters;

    @JsonProperty("name")
    @XmlElement(required = true)
    protected String name;

    @JsonProperty("origin")
    @XmlElement(required = true)
    protected String origin;

    @JsonProperty("preciousness")
    @XmlElement(required = true)
    protected String preciousness;

    @JsonProperty("value")
    protected float value;

    @XmlAttribute(name = "id")
    protected int id;

    public Gem() {
        visualParameters = new VisualParameters();
    }



    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the origin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the preciousness property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPreciousness() {
        return preciousness;
    }

    /**
     * Sets the value of the preciousness property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPreciousness(String value) {
        this.preciousness = value;
    }

    /**
     * Gets the value of the value property.
     */
    public float getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     */
    public void setValue(float value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setId(int value) {
        this.id = value;
    }

    @Override
    public String toString() {
        return "Gem{" +
                "visualParameters=" + visualParameters +
                ", name='" + name + '\'' +
                ", origin='" + origin + '\'' +
                ", preciousness='" + preciousness + '\'' +
                ", value=" + value +
                ", id=" + id +
                '}';
    }
}
